language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install: pip install coverage coveralls --use-mirrors
before_script: mkdir tests
script: make test && make coverage
after_success: coveralls
branches:
  only: master